learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users'))
]

learning_logs/urls.py
"""
定义learning_logs这个app内的urls
"""
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_topic/(?P<topic_id>\d+)/$', views.edit_topic, name='edit_topic'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry')
]

users/urls.py
"""
定义用户系统users这个app内的urls
"""
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    owner = models.ForeignKey(User)
    text = models.CharField('主题', max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """用户记录的具体条目"""
    topic = models.ForeignKey(Topic, verbose_name='主题')
    text = models.TextField('详细内容')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    """主题表单"""
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    """新增条目"""
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

learning_logs/views.py
from django.shortcuts import render
from learning_logs.models import Topic, Entry
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    """定义learning_logs首页的视图"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """定义所有主题的页面"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """显示单个主题内的详细条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """定义新增主题的form表单页面"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        # 对post提交的数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """定义新增详细条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        # 对post提交的数据进行处理
        form = EntryForm(request.POST)
        if form.is_valid():
            # 检验post数据的有效性
            new_entry = form.save(commit=False)# 不保存在数据中，把数据实例化为new_entry
            new_entry.topic = topic # 将这些数据的主题属性设置为这个函数开头从Topic中获取的相应主题topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic':topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """编辑修改条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'form': form, 'topic': topic, 'entry': entry}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def edit_topic(request, topic_id):
    """编辑修改主题名称"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout

# Create your views here.
def logout_view(request):
    """定义登出注销功能，不需要html页面"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册功能的实现"""
    if request.method != 'POST':
        # 显示空注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="Author" content="LiGuanNan">
    <meta name="Keywords" content="李冠男,学习笔记">
    <meta name="Description" content="这里是李冠男的学习笔记，不久的将来希望也能成为更多人记录学习笔记的地方。">
    <title>{% block title %}此处标题{% endblock title %} - 李冠男的个人学习笔记</title>
    <link href="/static/css/main.css" rel="stylesheet" type="text/css">
    {% block extracss %}{% endblock %}
</head>
<body>
<!--全局导航条-->
<div id="globllink">
    <ul>
      <li><a href="{% url 'learning_logs:index' %}">首页</a></li>
      <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
    </ul>
    <div id="globllink2">
        <ul>
          {% if user.is_authenticated %}
              <li>你好，{{ user.username }} <a href="{% url 'users:logout' %}">注销</a></li>
          {% else %}
              <li><a href="{% url 'users:login' %}">登录</a></li>
              <li><a href="{% url 'users:register' %}">注册</a></li>
          {% endif %}
        </ul>
    </div>
</div>
<!--整体外层容器-->
<div id="container">
    <!--中间内容栏-->
    <div>{% block content %}{% endblock content %}</div>
</div>

<!--footer-->
<div id="footer">
    &copy LiGuannan 个人学习笔记
</div>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block title %}编辑条目{% endblock title %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a><p>
<p>编辑条目：</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">保存更改</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends 'learning_logs/base.html' %}

{% block title %}修改主题{% endblock title %}

{% block content %}
    <p>修改主题：</p>
    <form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}    {# 用{{ form.as_p }}as_p是一种修饰符，让表单整洁的显示 #}
      <button name="submit">保存修改</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block title %}首页{% endblock title %}

{% block content %}
<p>
你可以在这里添加你要学习的主题，并且在主题内添加学习笔记
<p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block title %}添加新条目{% endblock title %}

{% block content %}
    <p>在<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>中添加新的条目：</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">提交</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block title %}新增主题{% endblock title %}

{% block content %}
    <p>新增主题：</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}    {# 用{{ form.as_p }}as_p是一种修饰符，让表单整洁的显示 #}
      <button name="submit">提交</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block title %}笔记详情 - {{ topic }}{% endblock title %}
{% block extracss %}<link href="/static/css/topic.css" rel="stylesheet" type="text/css">{% endblock extracss %}
{% block content%}
    <div id="topic">
        <div>
            <h5>{{ topic }}
                <span><a href="{% url 'learning_logs:new_entry' topic.id %}">新增条目</a></span></h5>

        </div>
        <ul>
          {% for entry in entries %}
              <li>
                  <h1>{{ entry.date_added|date:'Y年m月d日，H:i' }}
                      <span><a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑条目</a></span></h1>
                  <p>{{ entry.text|linebreaks }}</p>

              </li>
              {% empty %}
              <li>此主题下没有任何内容</li>
          {% endfor %}
        </ul>
    </div>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block title %}主题列表{% endblock title %}
{% block extracss %}<link href="/static/css/topics.css" rel="stylesheet" type="text/css">{% endblock extracss %}
{% block content %}
<div id="topics">
    <div>
        <h3><span>主题列表</span></h3>
        <ul>
          {% for topic in topics %}
              <li><a href="{% url 'learning_logs:edit_topic' topic.id %}">修改</a> |
                  <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
              </li>
          {% empty %}
            <li>没有更多的主题了</li>
          {% endfor %}
        </ul>
    </div>
    <h2><span><a href="{% url 'learning_logs:new_topic' %}">添加主题</a></span></h2>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html'%}

{% block title %}登录{% endblock title %}
    {% block extracss %}{% endblock %}

{% block content %}
<div style="text-align:center">
    <h3><span>登录</span></h3>
    {% if form.errors %}
        <p>咋治滴！错啦！重新输入！</p>
    {% endif %}
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">登录</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
        </form>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}

{% block title %}注册{% endblock title %}
{% block extracss %}<link href="/static/css/register.css" rel="stylesheet" type="text/css">{% endblock %}

{% block content %}
    <div id="register">
        <h3><span>欢迎注册</span></h3>
        <div>
            <form action="{% url 'users:register' %}" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button name="submit">注册</button>
              <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
            </form>
        </div>
    </div>
{% endblock content %}